platform.redis:
  image: "redis:${REDIS_VERSION}"
  volumes:
    "/root/redis":
      name: "${SERVICE}-data"
      config:
        driver: local
  expose:
    redis:
      type: static
      port: 6379
      pin: 6379
  labels:
    logging: "promtail-${ENVIRONMENT}"
    logging_jobname: "platform.redis"
  envmap:
    REDIS_PASSWORD: "${SECRET_REDIS_PASSWORD}"
