platform.redis:
  image: "redis:${REDIS_VERSION}"
  volumes:
    "/root/redis":
      name: "${ENVIRONMENT}-${SERVICE}-data"
      config:
        driver: local
  expose:
    redis:
      type: static
      port: 6379
      pin: 6379
  envmap:
    REDIS_PORT: "${EXPOSE_STATIC_REDIS}"
    REDIS_PASSWORD: "${SECRET_REDIS_PASSWORD}"
