syntax = "proto3";
option csharp_namespace = "Meowmentum.Server.Dotnet.Proto.Email";
option go_package = "./email";

service EmailService {
  rpc RegistrationConfirmation (RegistrationConfirmationRequest) returns (RegistrationConfirmationResponse);
  rpc PasswordReset (PasswordResetRequest) returns (PasswordResetResponse);
  rpc SendNotification (SendNotificationRequest) returns (SendNotificationResponse);
}

message RegistrationConfirmationRequest {
  string Email = 1;
  string Name = 2;
  string ConfirmationCode = 3;
}

message RegistrationConfirmationResponse {}

message PasswordResetRequest {
  string Email = 1;
  string Name = 2;
  string ConfirmationCode = 3;
}

message PasswordResetResponse {}

message SendNotificationRequest {
  string Email = 1;
  string Message = 2;
}

message SendNotificationResponse {}