service.dotnet:
  image: "${ENVIRONMENT}-${SERVICE}:${GIT_COMMIT}"
  build:
    context: "/backend"
    dockerfile: "/backend/dotnet/Meowmentum.Server.Dotnet.Api/Dockerfile"
    additional_contexts:
      proto: "/backend/proto"
    target: final
  expose:
    http:
      type: http
      routes:
        "/api/core/": "/"
  attach:
    - platform.postgres:postgres
    - platform.redis:redis
    - service.go.email:email
  envpass:
    - SECRET_POSTGRES_USERNAME
    - SECRET_POSTGRES_PASSWORD
    - SECRET_POSTGRES_DATABASE
    - SECRET_REDIS_PASSWORD
    - SECRET_JWT_KEY
    - ATTACH_GRPC_EMAIL
  envmap:
    ConnectionString__MasterDatabase: "Server=localhost;Database=${SECRET_POSTGRES_DATABASE};Port=5432;User Id=${SECRET_POSTGRES_USERNAME};Password=${SECRET_POSTGRES_PASSWORD};Include Error Detail=false;"   #??? Can mapper handdle combination of envs in string??
    JwtSettings__Key: "${SECRET_JWT_KEY}"
    RedisConfiguration__RedisConnection__Password: "${SECRET_REDIS_PASSWORD}"
    Grpc__EmailOptions__Address: "${ATTACH_GRPC_EMAIL}"
    ASPNETCORE_URLS: "http://${EXPOSE_HTTP}" #??? Can mapper handdle combination of envs in string??



