service.web:
  image: '${ENVIRONMENT}-${SERVICE}:${GIT_COMMIT}'
  build:
    context: '.'
    target: runner
  expose:
    http:
      type: http
      routes:
        '/': '/'
  split_address_parts: true
  envmap:
    ATTACH_API_ENDPOINT: '/api'
    PORT: '${EXPOSE_HTTP_PORTPART}'
