{
 "title": "Main",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 20, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=~\".+\"} | pattern `<_log_message>` | line_format \"{{.service}}: {{._log_message}}\""
    }
   ]
  },
  {
   "title": "Requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "count by(service) (count_over_time({service=\"platform.nginx\"} | json | request_method = `GET` [1m]))",
     "legendFormat": "GET"
    },
    {
     "expr": "count by(service) (count_over_time({service=\"platform.nginx\"} | json | request_method = `POST` [1m]))",
     "legendFormat": "POST"
    },
    {
     "expr": "count by(service) (count_over_time({service=\"platform.nginx\"} | json | request_method = `PUT` [1m]))",
     "legendFormat": "PUT"
    },
    {
     "expr": "count by(service) (count_over_time({service=\"platform.nginx\"} | json | request_method = `PATCH` [1m]))",
     "legendFormat": "PATCH"
    },
    {
     "expr": "count by(service) (count_over_time({service=\"platform.nginx\"} | json | request_method = `DELETE` [1m]))",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Most popular endpoints",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 7 },
   "targets": [
    {
     "expr": "{service=\"platform.nginx\"} | json | request_method=~\".+\""
    }
   ]
  },
  {
   "title": "Log level distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{service=~\".+\"} | detected_level=~\".+\" | line_format \"{{ .detected_level | upper }}\""
    }
   ]
  }
 ]
}