platform.postgres:
  image: "postgres:${POSTGRES_VERSION}"
  volumes:
    "/var/lib/postgresql/data":
      name: "${SERVICE}-data"
      config:
        driver: local
  expose:
    postgres:
      type: static
      port: 5432
      pin: 5432
  labels:
    logging: "promtail-${ENVIRONMENT}"
    logging_jobname: "platform.postgres"
  envmap:
    POSTGRES_USER: "${SECRET_POSTGRES_USERNAME}"
    POSTGRES_PASSWORD: "${SECRET_POSTGRES_PASSWORD}"
    POSTGRES_DB: "${SECRET_POSTGRES_DATABASE}"
