platform.nginx:
  image: "${ENVIRONMENT}-${SERVICE}:${GIT_COMMIT}"
  build:
    context: "."
    additional_contexts:
      gen: "gen:nginx ./template.conf"
    args:
      NGINX_VERSION: "${NGINX_VERSION}"
  labels:
    logging: "promtail-${ENVIRONMENT}"
    logging_jobname: "platform.nginx"
  expose:
    http:
      type: static
      port: 8080
      pin: 8080
