name: CI Web

on:
  push:
    branches:
      - main
      - web  
  pull_request:
    branches:
      - main
      - web  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.0'

      - name: Install dependencies
        working-directory: ./web/meowmentum/
        run: yarn install

      - name: Run lint
        working-directory: ./web/meowmentum/
        run: yarn lint

      - name: Run format check
        working-directory: ./web/meowmentum/
        run: yarn format

      - name: Build the application
        working-directory: ./web/meowmentum/
        run: yarn build
        
