name: CI Web

on:
  push:
    branches:
      - main
      - dev  
    paths:
      - 'web/meowmentum/**'
  pull_request:
    branches:
      - main
      - dev  
    paths:
      - 'web/meowmentum/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: yarn install
        working-directory: web/meowmentum

      - name: Run lint
        run: yarn lint
        working-directory: web/meowmentum

      - name: Run format check
        run: yarn format
        working-directory: web/meowmentum

      - name: Build the application
        run: yarn build
        working-directory: web/meowmentum
        
